plugins {
    id 'java'
}

group = 'com.oodesigns'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Testing
    testImplementation platform('org.junit:junit-bom:5.11.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.12.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.12.0'
    
    // Main dependencies
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.0'
    implementation 'com.bucket4j:bucket4j_jdk17-core:8.15.0'
}

test {
    useJUnitPlatform()
}